repos:
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c ' ./docker-flask/venv/bin/pip3 freeze > ./docker-flask/requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
